### ISSUE TITLE
I am getting this error, what do I do?

### ISSUE THREAD

**Issue by duradara** [EmaOlay/E7-Auto-Shop-Refresh#2]
![Screenshot 2020-11-20 130310](https://user-images.githubusercontent.com/50158352/99821492-e2e4c480-2b30-11eb-89b9-3be2025c091d.png)

**Comment by EmaOlay** [comment]
It seems that you did not install pyautogui.
Here's link:
https://pyautogui.readthedocs.io/en/latest/install.html

**Comment by duradara** [comment]
Okey now I am getting this error.
![Screenshot 2020-11-20 131847](https://user-images.githubusercontent.com/50158352/99823295-f7c25780-2b32-11eb-8576-38b9025706f9.png)
Do you have a list of mudules that I have to install?

**Comment by EmaOlay** [comment]
In case any other "Missing module" error pops up it's probably because it's not installed.
I believe all the modules I used were these:
pip install pywin32
pip install keyboard
pip install pyautogui
pip install opencv-python

**Comment by duradara** [comment]
How do I install these?

**Comment by EmaOlay** [comment]
The same way you just intalled pyautogui, open the console and type the commands I just wrote.

**Comment by duradara** [comment]
Thx I forgot to add "py -m" at the start.  
Whilie instaling opencv-python i got this warning;
![Screenshot 2020-11-20 134926](https://user-images.githubusercontent.com/50158352/99826515-39ed9800-2b37-11eb-8399-69ab81008cdc.png)  
Should I care? if so, how do I add this to path?

**Comment by EmaOlay** [comment]
Mmmm I believe it is not necesary to add it to path  since it's only a warning but if any error pops up tell me and I'll find a way to add it to path.

**Comment by duradara** [comment]
I fount how to add it to path thanx to [this](https://www.reddit.com/r/learnpython/comments/buyeya/how_to_add_directories_to_the_path/) but now I get this error,
![Screenshot 2020-11-20 134926](https://user-images.githubusercontent.com/50158352/99827440-5fc76c80-2b38-11eb-8664-034369a2844e.png)
Sorry for all the question I am asking.

**Comment by EmaOlay** [comment]
It's fine I appreciate your interest, all error appear in __init__.py, have you tried looking into that tiyurl?
It seems to have something to do with numpy, maybe reinstalling could fix this issue.
Is it your first time running a python script? if it is I would suggest using a distro like anaconda and re running the commands mentioned above in the anaconda promt.
