### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by kuynh** [EmaOlay/E7-Auto-Shop-Refresh#5]
Error occurs when running script. Here is the log to go along with it.

(base) C:\Users\kuynh\Documents\E7-Auto-Shop-Refresh-main>python AutoRefresh.py
Traceback (most recent call last):
  File "AutoRefresh.py", line 102, in <module>
    RB_point=pyautogui.center(RB_pos)
  File "C:\Users\huynh\anaconda3\lib\site-packages\pyscreeze\__init__.py", line 582, in center
    return Point(coords[0] + int(coords[2] / 2), coords[1] + int(coords[3] / 2))
TypeError: 'NoneType' object is not subscriptable

**Comment by EmaOlay** [comment]
It's unable to recognice the Refresh button so in a previous instance so when pyautogui.center() tries to find it's center it tells you it's unable to do that for a NoneType object
